### ISSUE TITLE
Week 0: Individual Jekyll page

### ISSUE THREAD

**Issue by shrutiapcsp** [shrutiapcsp/Shruti-Individual-#1]
[Link to page
](https://shrutiapcsp.github.io/Shruti-Individual-/)
- [x] Create task page
- [x] Data Structures project
- [x] Test Prep

**Comment by sanvi1855544** [comment]
**FINAL SCORE: 2.8/3**

**1) GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))**

The notes were very thorough. The GitHub action responses were also very thoughtful. No deduction on this part.


**2) GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime**


Repl Code was linked. However, need to put screenshot of code snippets (-0.2 deduction)

**3) GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime**

Everything is linked and well organized.
