### ISSUE TITLE
Week 1: Lists & Loops

### ISSUE THREAD

**Issue by shrutiapcsp** [shrutiapcsp/Shruti-Individual-#2]
**_TOTAL SCORE: 4.4/5_**
[Link to Github Page](https://shrutiapcsp.github.io/Shruti-Individual-/)
- [x] Test Prep study: 5.3, 5.4 notes and actions
- [x] Data structures: key learnings and code snippets using GitHub and replit.
- InfoDB lists
- InfoDB loops
- Fibonacci

**Comment by nataliecohen** [comment]
**Corrected by: Natalie Cohen**
Individual GitHub pages (3 points)
GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions 
1/1- One Check 5.3 
1/1- One Check 5.4 
GitHub page that documents key learnings and code snippets using GitHub and replit.
InfoDB lists
1 /1 - One Check for New Data, minimum of 4 items
InfoDB loops
1/1- One Check For Loop running and sensible output
1/1- One Check While Loop running and sensible output
1/1- One Check Recursion running and sensible output
1.5/2 Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term) - Missing special characters 
4- Four checks: Algorithm and code with comments, Prints result, Prints Complete List, Work on complex sequence with multiple words, spaces, special characters
.5/1- One check: comments and documentation throughout
**Individual: 10/11 = 2.7/3  + Team Score 1.8/2
**Total Score: 4.4/5**** 
Had everything visible and organized on GitHub Pages. Replit was included along with runtime. List and loops was very well done, inclusion of own data. All 3 types of loops worked. Fibonacci was lacking use of special characters, but ran efficiently. There could be an addition to comments made when documenting code.
