### ISSUE TITLE
Week 2: Classy

### ISSUE THREAD

**Issue by shrutiapcsp** [shrutiapcsp/Shruti-Individual-#3]
**_FINAL GRADE: 4.5/5_**
Self Grade 2.55/3 + 2/2 = 4.5/5
GitHub page that documents key learnings and code snippets using GitHub and replit 

- [x] Organize files, directories and menus for the first 3 weeks. 
- [x] Write Factorial function using classes, providing implementation of call.
- [x] Select your own Math function. Write it in Imperative and OOP form.
- [ ] Extra Credit.  Write Palindrome function using classes, must provide implementation of call.Must indicate where error occurs on front and back comparison.

Self Grade:

- Organization: include full code in the menu -0.2
- Factorial: complete -0.25
- Math: complete
- Extra Credit: none

**Comment by hamzahakak** [comment]
4.5/5 TOTAL

2.5/3 INDIVIDUAL
2/2 SCRUM

-.25 organization needs a little work
-.25 factorial classes not complete but almost there :)
