### ISSUE TITLE
Week 3: Algorithmic Final

### ISSUE THREAD

**Issue by shrutiapcsp** [shrutiapcsp/Shruti-Individual-#4]
**_CROSSOVER GRADE: 9.5/10_**

[Github Page](https://shrutiapcsp.github.io/Shruti-Individual-/)
[Replit](https://replit.com/@shrutiapcsp/shrutidatastructures#challenges/menu.py)
[Video](https://www.youtube.com/watch?v=LPF_cqMayjo)
- [x] [Commits](https://github.com/shrutiapcsp/Shruti-Individual-/commits/main?after=aef9e36c942e7853de17763451e42689315df9a9+69&branch=main)/[Insights](https://github.com/shrutiapcsp/Shruti-Individual-/graphs/contributors)
- [x] Code running on Replit and IntelliJ
- [x] Crossover [Commits](https://github.com/nataliecohen/nataliecohen.github.io/commits/main)

Self Grade: 9.4/10
- 0.2 could have explained more about menu organization but was limited by 2 minute time
- 0.1 could have added more to crossover code like images or changes in format
- 0.3 could have included more comments throughout in all code

**Comment by sanvi1855544** [comment]
9.5/10

She hit all of the MyConnect bullet points and the video was under 2 minutes. My deduction was because she could have documented/commented more. Also she could've explained the code/algos more.
