### ISSUE TITLE
Week 5: Accounts and Logins

### ISSUE THREAD

**Issue by shrutiapcsp** [shrutiapcsp/Shruti-Individual-#6]
**_FINAL GRADE: 4.5/5_**

Self Grade: 4.25/5
- [x] Create Task: 2/2 (video with audio VoiceOver and runtime of code, documentation with CB write-up, and code commit is linked on GitHub page)
- [x] Accounts and Logins Challenge: 2.25/3 (first two hacks complete but hack 3 but is not working, still attempted)

**Comment by nataliecohen** [comment]
**Natalie Cohen Grade of Shruti: 4.5/5**

1.  Create Task: 2/2 - very cool idea, had an efficient video that displayed her create task video, able to see that effort and knowledge was there. 

2.  Accounts and Logins Challenge: 2.5/3 (attempted hack 3 but is not working)
Runtime of the Crud worked, only hack that did not work was hack 3 (was attempted and he effort was shown but it was not able to run).
